### PR TITLE
Adding login workflow change announcements.

### PR DESCRIPTION
**Pull request by jrbenn**

### CODE REVIEW

**Comment by adamc00** [comment]
@jrbenn, it's failing a check of some kind. Also, have you looked at how that is rendering in context?

**Comment by adamc00** [comment]
I suspect you're better off just adding one that summarises the situation without trying to recreate the full HTML.

**Comment by jrbenn** [comment]
@adamc00 - it's failing due to obsolete html elements like align on table. I'll have to fix that, but it was rendering very nicely, which I was actually rather pleased with...

**Comment by adamc00** [comment]
Nice! Yeah, email clients require some very "special" HTML to behave  correctly.

**Comment by jrbenn** [comment]
@adamc00 the checks are now passing. Can you approve the review?

**Review by adamc00 — APPROVED** [review]
🏃 👍

**Pull request merged**
